configure configure.in   - Tabs --> spaces, indenting uniformity, and typo corrections only.

diff --git a/client/trunk/configure b/client/trunk/configure
--- a/client/trunk/configure
+++ b/client/trunk/configure
@@ -878,17 +878,17 @@ Optional Features:
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
   --disable-dependency-tracking  speeds up one-time build
   --enable-dependency-tracking   do not reject slow dependency extractors
-  --enable-debug          turn on debugging default=no
-  --enable-ansi           turn on strict ansi default=no
-  --disable-sound         disable sound support default=implement sound support if supported libraries exist
-  --disable-alsa9         disable ALSA9 sound support default=use alsa9 sound support if alsa9 libraries exist
-  --disable-alsa          disable ALSA sound support default=use alsa sound support if alsa libraries exist
-  --disable-gtkv1         do not make original gtk client default=make it if available
-  --disable-gtkv2         do not make gtk-v2 client default=make it if available
-  --enable-cfgtk2         enable building the original gtkv1 client with GTK+ 2
-  --disable-sdl           disable linking with the SDL library, default is to use it if available
-  --enable-dmalloc        enable checking for dmalloc library, default is to use it if available
-  --disable-metaserver2       Do not build in metaserver2 support
+  --enable-debug          Turn on debugging default=no
+  --enable-ansi           Turn on strict ansi default=no
+  --disable-sound         Disable sound support default=implement sound support                           if supported libraries exist
+  --disable-alsa9         Disable ALSA9 sound support default=use alsa9 sound                             support if alsa9 libraries exist
+  --disable-alsa          Disable ALSA sound support default=use alsa sound                               support if alsa libraries exist
+  --disable-gtkv1         Do not make original gtk client default=make it if                              available
+  --disable-gtkv2         Do not make gtk-v2 client default=make it if available
+  --enable-cfgtk2         Enable building the original gtkv1 client with GTK+ 2
+  --disable-sdl           Disable linking with the SDL library, default is to                              use it if available
+  --enable-dmalloc        Enable checking for dmalloc library, default is to use it if available
+  --disable-metaserver2   Do not build in metaserver2 support
   --disable-gtktest       Do not try to compile and run a test GTK program
   --enable-maintainer-mode  enable make rules and dependencies not useful
 			  (and sometimes confusing) to the casual installer
@@ -898,10 +898,10 @@ Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-x                use the X Window System
-  --with-sound-dir=dir    directory where the sounds are located (default=/usr/local/lib/sounds)
-  --with-ldflags=dir      provide addition linker directives to find libraries
-  --with-includes=dir     provide different compiler options to find headers with
-  --with-logevel=level    sets default loglevel
+  --with-sound-dir=dir    Directory where the sounds are located                                          (default=/usr/local/lib/sounds)
+  --with-ldflags=dir      Provide additional linker directives to find libraries
+  --with-includes=dir     Provide different compiler options to find headers                               with
+  --with-logevel=level    Sets default loglevel
   --with-gtk-prefix=PFX   Prefix where GTK is installed (optional)
   --with-gtk-exec-prefix=PFX Exec prefix where GTK is installed (optional)
   --with-sdl-prefix=PFX   Prefix where SDL is installed (optional)
@@ -4990,7 +4990,7 @@ SOUNDDIR="${datadir}/crossfire-client/sounds"
 if test "${enable_debug+set}" = set; then
   enableval="$enable_debug"
   if eval "test x$enable_debug = xyes"; then
-  DEBUGFLAG="-g"
+    DEBUGFLAG="-g"
 fi
 fi;
 
@@ -5001,7 +5001,6 @@ if test "${enable_ansi+set}" = set; then
 else
   enable_ansi=$enableval
 fi;
-
 
 # Check whether --enable-sound or --disable-sound was given.
 if test "${enable_sound+set}" = set; then
@@ -5037,7 +5036,6 @@ fi;
 
 
 
-
 # Check whether --with-ldflags or --without-ldflags was given.
 if test "${with_ldflags+set}" = set; then
   withval="$with_ldflags"
@@ -5052,7 +5050,6 @@ if test "${with_includes+set}" = set; then
 fi;
 
 
-
 # Check whether --with-loglevel or --without-loglevel was given.
 if test "${with_loglevel+set}" = set; then
   withval="$with_loglevel"
@@ -5060,7 +5057,6 @@ if test "${with_loglevel+set}" = set; then
 else
   MINLOGLEVEL=0
 fi;
-
 
 # Check whether --enable-gtkv1 or --disable-gtkv1 was given.
 if test "${enable_gtkv1+set}" = set; then
@@ -6182,33 +6178,33 @@ esac
 
 networklibs="yes"
 
-
 case "$target" in
-  alpha-dec-osf*)
-    # If we are not using gcc, we want the ansi version of cc.
-    if test -z "$GCC"; then
-#      CFLAGS="$CFLAGS -std1 -warnprotos" # Not yet ready for warnprotos...
-      CFLAGS="$CFLAGS -std1"
-    fi
+    alpha-dec-osf*)
+        # If we are not using gcc, we want the ansi version of cc.
+        if test -z "$GCC"; then
+        #   CFLAGS="$CFLAGS -std1 -warnprotos" # Not yet ready for warnprotos...
+            CFLAGS="$CFLAGS -std1"
+        fi
     ;;
-    mips*-sgi-irix*)
-	networklibs="no"
-	;;
-    *-linux-*)
-	networklibs="no"
-	;;
-  *-*-solaris2*)
-	need_r_flag="yes"
-	;;
-  *-*-mingw32*)
-    win32="yes"
-    # -mms-bitfields is needed for GTK+ in windows.  It is set automatically
-    # by pkg-config, but it's also needed in common, so we explicitely set it
-    CFLAGS="$CFLAGS -mms-bitfields"
-    WIN32_LIBS="-lwsock32 -lwinmm"
+        mips*-sgi-irix*)
+        networklibs="no"
+    ;;
+        *-linux-*)
+        networklibs="no"
+    ;;
+    *-*-solaris2*)
+        need_r_flag="yes"
+    ;;
+    *-*-mingw32*)
+        win32="yes"
+        # -mms-bitfields is needed for GTK+ in Windows.  It is set
+        # automatically by pkg-config, but it is also needed in common, so we
+        # explicitely set it
+        CFLAGS="$CFLAGS -mms-bitfields"
+        WIN32_LIBS="-lwsock32 -lwinmm"
 
     ;;
-  *)
+    *)
     ;;
 esac
 
@@ -6739,7 +6735,7 @@ echo "$as_me: GTK 1 found - building gtk client" >&6;}
 
 
              CF_SUBDIRS="$CF_SUBDIRS gtk"
-                       else
+                     else
             { echo "$as_me:$LINENO: WARNING: GTK 1 not found - not building building gtk-v1 client" >&5
 echo "$as_me: WARNING: GTK 1 not found - not building building gtk-v1 client" >&2;}
         fi
@@ -6935,7 +6931,6 @@ else
 fi
 
   MAINT=$MAINTAINER_MODE_TRUE
-
 
 
 
@@ -8030,8 +8025,8 @@ if eval "test x$need_r_flag = xyes"; then
 fi
 
 if eval "test x$sound = xyes"; then
-  if eval "test x$alsa = xyes"; then
-    echo "$as_me:$LINENO: checking for main in -lasound" >&5
+    if eval "test x$alsa = xyes"; then
+        echo "$as_me:$LINENO: checking for main in -lasound" >&5
 echo $ECHO_N "checking for main in -lasound... $ECHO_C" >&6
 if test "${ac_cv_lib_asound_main+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -8093,8 +8088,8 @@ if test $ac_cv_lib_asound_main = yes; then
   alsa_sound=yes
 fi
 
-  fi
-  echo "$as_me:$LINENO: checking for alNewConfig in -laudio" >&5
+    fi
+    echo "$as_me:$LINENO: checking for alNewConfig in -laudio" >&5
 echo $ECHO_N "checking for alNewConfig in -laudio... $ECHO_C" >&6
 if test "${ac_cv_lib_audio_alNewConfig+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -8162,8 +8157,8 @@ if test $ac_cv_lib_audio_alNewConfig = yes; then
   sgi_sound=yes
 fi
 
-  if eval "test x$alsa9 = xyes"; then
-    echo "$as_me:$LINENO: checking for egrep" >&5
+    if eval "test x$alsa9 = xyes"; then
+        echo "$as_me:$LINENO: checking for egrep" >&5
 echo $ECHO_N "checking for egrep... $ECHO_C" >&6
 if test "${ac_cv_prog_egrep+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -8560,8 +8555,8 @@ else
 fi
 
 
-  fi
-  if test "${ac_cv_header_sys_soundcard_h+set}" = set; then
+    fi
+    if test "${ac_cv_header_sys_soundcard_h+set}" = set; then
   echo "$as_me:$LINENO: checking for sys/soundcard.h" >&5
 echo $ECHO_N "checking for sys/soundcard.h... $ECHO_C" >&6
 if test "${ac_cv_header_sys_soundcard_h+set}" = set; then
@@ -8705,7 +8700,7 @@ else
 fi
 
 
-  if test "${ac_cv_header_sys_audioio_h+set}" = set; then
+    if test "${ac_cv_header_sys_audioio_h+set}" = set; then
   echo "$as_me:$LINENO: checking for sys/audioio.h" >&5
 echo $ECHO_N "checking for sys/audioio.h... $ECHO_C" >&6
 if test "${ac_cv_header_sys_audioio_h+set}" = set; then
@@ -8851,33 +8846,33 @@ fi
 
 
 
-  if eval "test x$alsa9_sound = xyes"; then
-	echo "Using ALSA sound system (0.9.x)"
-	CFLAGS="$CFLAGS -DALSA9_SOUND"
-	ALSA9_TARGET='cfsndserv_alsa9$(EXEEXT)'
-	ALSA9_LIBS="-lasound -lm"
-	SOUND_SRC="sound-src";
+    if eval "test x$alsa9_sound = xyes"; then
+        echo "Using ALSA sound system (0.9.x)"
+        CFLAGS="$CFLAGS -DALSA9_SOUND"
+        ALSA9_TARGET='cfsndserv_alsa9$(EXEEXT)'
+        ALSA9_LIBS="-lasound -lm"
+        SOUND_SRC="sound-src";
 
-					alsa_sound="no";
-   fi
+                                        alsa_sound="no";
+    fi
 
     if eval "test x$alsa_sound = xyes"; then
-  	echo "Using ALSA sound system"
-  	CFLAGS="$CFLAGS -DALSA_SOUND"
-  	SND_LIBS="-lasound -lm"
-	SOUND_SRC="sound-src";
+        echo "Using ALSA sound system"
+        CFLAGS="$CFLAGS -DALSA_SOUND"
+        SND_LIBS="-lasound -lm"
+        SOUND_SRC="sound-src";
     else
-      if eval "test x$sgi_sound = xyes"; then
-	echo "Using SGI sound system"
-  	CFLAGS="$CFLAGS -DSGI_SOUND"
-  	SND_LIBS="-laudio"
-	SOUND_SRC="sound-src";
-      else
-        if eval "test x$oss_sound = xyes"; then
-	  echo "Using OSS sound system"
-	  CFLAGS="$CFLAGS -DOSS_SOUND"
-	  SND_LIBS="-lm"
-	  echo "$as_me:$LINENO: checking for main in -lossaudio" >&5
+        if eval "test x$sgi_sound = xyes"; then
+            echo "Using SGI sound system"
+            CFLAGS="$CFLAGS -DSGI_SOUND"
+            SND_LIBS="-laudio"
+            SOUND_SRC="sound-src";
+        else
+            if eval "test x$oss_sound = xyes"; then
+                echo "Using OSS sound system"
+                CFLAGS="$CFLAGS -DOSS_SOUND"
+                SND_LIBS="-lm"
+                echo "$as_me:$LINENO: checking for main in -lossaudio" >&5
 echo $ECHO_N "checking for main in -lossaudio... $ECHO_C" >&6
 if test "${ac_cv_lib_ossaudio_main+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -8939,20 +8934,20 @@ if test $ac_cv_lib_ossaudio_main = yes; then
   SND_LIBS="$LIBS -lossaudio"
 fi
 
-	  SOUND_SRC="sound-src";
-        else
-          if eval "test x$sun_sound = xyes"; then
-  	      echo "Using solaris sound system"
-  	      CFLAGS="$CFLAGS -DSUN_SOUND"
-  	      SND_LIBS="-lm"
-	      SOUND_SRC="sound-src";
-  	  else
-  	      echo "No suitable sound system found."
-          fi
+                SOUND_SRC="sound-src";
+            else
+                if eval "test x$sun_sound = xyes"; then
+                    echo "Using solaris sound system"
+                    CFLAGS="$CFLAGS -DSUN_SOUND"
+                    SND_LIBS="-lm"
+                    SOUND_SRC="sound-src";
+                else
+                    echo "No suitable sound system found."
+                fi
+            fi
         fi
-      fi
     fi
-  # this fi is for the sound == yes check above
+    # this fi is for the sound == yes check above
 fi
 
 if eval "test x$SOUND_SRC != x"; then
@@ -9267,8 +9262,8 @@ rm -f conftest.err conftest.$ac_objext \
   rm -f conf.sdltest
 
 
-if eval "test x$no_sdl = x"; then
-     echo "$as_me:$LINENO: checking for IMG_LoadPNG_RW in -lSDL_image" >&5
+    if eval "test x$no_sdl = x"; then
+        echo "$as_me:$LINENO: checking for IMG_LoadPNG_RW in -lSDL_image" >&5
 echo $ECHO_N "checking for IMG_LoadPNG_RW in -lSDL_image... $ECHO_C" >&6
 if test "${ac_cv_lib_SDL_image_IMG_LoadPNG_RW+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -9338,53 +9333,52 @@ else
   have_sdlimage="no"
 fi
 
-     if eval "test x$have_sdlimage = xyes"; then
-         SDL_LIBS="$SDL_LIBS -lSDL_image"
-     fi
- fi
+        if eval "test x$have_sdlimage = xyes"; then
+            SDL_LIBS="$SDL_LIBS -lSDL_image"
+        fi
+    fi
 
-  if eval "test x$no_sdl = x"; then
+    if eval "test x$no_sdl = x"; then
 
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_SDL 1
 _ACEOF
 
-  fi
+    fi
 fi
 
 
 
 
 if test -n "$DEBUGFLAG"; then
-  CFLAGS="$DEBUGFLAG $CFLAGS"
+    CFLAGS="$DEBUGFLAG $CFLAGS"
 fi
 
 if eval "test x$GCC = xyes"; then
-  if echo "$CFLAGS" | grep "\-Wall" > /dev/null 2> /dev/null; then
-    CFLAGS="$CFLAGS"
-  else
-    CFLAGS="$CFLAGS -Wall"
-  fi
-
-  if eval "test x$enable_ansi = xyes"; then
-    if echo "$CFLAGS" | grep "\-ansi" > /dev/null 2> /dev/null; then
-      CFLAGS="$CFLAGS"
+    if echo "$CFLAGS" | grep "\-Wall" > /dev/null 2> /dev/null; then
+        CFLAGS="$CFLAGS"
     else
-      CFLAGS="$CFLAGS -ansi"
+        CFLAGS="$CFLAGS -Wall"
     fi
 
-    if echo "$CFLAGS" | grep "\-pedantic" > /dev/null 2> /dev/null; then
-      CFLAGS="$CFLAGS"
-    else
-      CFLAGS="$CFLAGS -pedantic"
+    if eval "test x$enable_ansi = xyes"; then
+        if echo "$CFLAGS" | grep "\-ansi" > /dev/null 2> /dev/null; then
+            CFLAGS="$CFLAGS"
+        else
+            CFLAGS="$CFLAGS -ansi"
+        fi
+
+        if echo "$CFLAGS" | grep "\-pedantic" > /dev/null 2> /dev/null; then
+            CFLAGS="$CFLAGS"
+        else
+            CFLAGS="$CFLAGS -pedantic"
+        fi
     fi
-  fi
 fi
 
 
-
 if eval "test x$networklibs = xyes"; then
-  echo "$as_me:$LINENO: checking for main in -lnsl" >&5
+    echo "$as_me:$LINENO: checking for main in -lnsl" >&5
 echo $ECHO_N "checking for main in -lnsl... $ECHO_C" >&6
 if test "${ac_cv_lib_nsl_main+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -9446,7 +9440,7 @@ if test $ac_cv_lib_nsl_main = yes; then
   LIBS="$LIBS -lnsl"
 fi
 
-  echo "$as_me:$LINENO: checking for main in -lsocket" >&5
+    echo "$as_me:$LINENO: checking for main in -lsocket" >&5
 echo $ECHO_N "checking for main in -lsocket... $ECHO_C" >&6
 if test "${ac_cv_lib_socket_main+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -10097,7 +10091,6 @@ CPPFLAGS="$CPPFLAGS $LIBCURL_CPPFLAGS"
 
 
 
-
 echo "$as_me:$LINENO: checking for main in -lz" >&5
 echo $ECHO_N "checking for main in -lz... $ECHO_C" >&6
 if test "${ac_cv_lib_z_main+set}" = set; then
@@ -10565,11 +10558,11 @@ done
 
 
 if eval "test x$ac_cv_header_curl_curl_h = xno" ; then
-   if eval "test x$metaserver2 = xyes"; then
-	{ { echo "$as_me:$LINENO: error: curl/curl.h header not found, but metaserver2 support is enable.  Install header file or use --disable-metaserver2" >&5
-echo "$as_me: error: curl/curl.h header not found, but metaserver2 support is enable.  Install header file or use --disable-metaserver2" >&2;}
+    if eval "test x$metaserver2 = xyes"; then
+        { { echo "$as_me:$LINENO: error: curl/curl.h header not found, but metaserver2 support is enabled.  Install header file or use --disable-metaserver2" >&5
+echo "$as_me: error: curl/curl.h header not found, but metaserver2 support is enabled.  Install header file or use --disable-metaserver2" >&2;}
    { (exit 1); exit 1; }; };
-   fi
+    fi
 fi
 
 if eval "test x$metaserver2 = xyes"; then
@@ -10586,9 +10579,8 @@ _ACEOF
 
 fi
 
-
 if eval "test x$use_dmalloc = xyes"; then
-	echo "$as_me:$LINENO: checking for main in -ldmalloc" >&5
+    echo "$as_me:$LINENO: checking for main in -ldmalloc" >&5
 echo $ECHO_N "checking for main in -ldmalloc... $ECHO_C" >&6
 if test "${ac_cv_lib_dmalloc_main+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -11805,7 +11797,6 @@ _ACEOF
 
 
 
-
 if test $ac_cv_c_compiler_gnu = yes; then
     echo "$as_me:$LINENO: checking whether $CC needs -traditional" >&5
 echo $ECHO_N "checking whether $CC needs -traditional... $ECHO_C" >&6
@@ -12200,7 +12191,6 @@ _ACEOF
 cat >>confdefs.h <<_ACEOF
 #define MINLOGLEVEL ${MINLOGLEVEL}
 _ACEOF
-
 
 
 
@@ -13697,4 +13687,5 @@ if test "$no_create" != yes; then
   # would make configure fail if this is the last instruction.
   $ac_cs_success || { (exit 1); exit 1; }
 fi
+
 
